app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(search_text = "october")
app$setInputs(trykk = "click")
app$snapshot()
app$setInputs(corpus_box = "Corpus info")
app$snapshot()
app$setInputs(corpus_box = "korpuskart_tab")
app$setInputs(modus = "data_dok")
app$setInputs(trykk = "click")
app$snapshot()
